package com.leafsoft.persistance;
// Generated Dec 4, 2016 10:43:15 PM by Hibernate Tools 3.6.0.Final

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * ExamType generated by hbm2java
 */
@Entity
@Table(name = "ExamType", catalog = "userdb")
public class ExamType implements java.io.Serializable {

	private Integer examtypeid;
	private String examtypename;
	private Boolean status;

	public ExamType() {
	}

	public ExamType(String examtypename) {
		this.examtypename = examtypename;
	}

	public ExamType(String examtypename, Boolean status) {
		this.examtypename = examtypename;
		this.status = status;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "examtypeid", unique = true, nullable = false)
	public Integer getExamtypeid() {
		return this.examtypeid;
	}

	public void setExamtypeid(Integer examtypeid) {
		this.examtypeid = examtypeid;
	}

	@Column(name = "examtypename", nullable = false, length = 100)
	public String getExamtypename() {
		return this.examtypename;
	}

	public void setExamtypename(String examtypename) {
		this.examtypename = examtypename;
	}

	@Column(name = "status")
	public Boolean getStatus() {
		return this.status;
	}

	public void setStatus(Boolean status) {
		this.status = status;
	}

}
