package com.leafsoft.persistance;
// Generated Dec 4, 2016 10:43:15 PM by Hibernate Tools 3.6.0.Final

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * ExamDetails generated by hbm2java
 */
@Entity
@Table(name = "ExamDetails", catalog = "userdb")
public class ExamDetails implements java.io.Serializable {

	private Integer examid;
	private String examname;
	private int examtypeid;
	private Boolean status;

	public ExamDetails() {
	}

	public ExamDetails(String examname, int examtypeid) {
		this.examname = examname;
		this.examtypeid = examtypeid;
	}

	public ExamDetails(String examname, int examtypeid, Boolean status) {
		this.examname = examname;
		this.examtypeid = examtypeid;
		this.status = status;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "examid", unique = true, nullable = false)
	public Integer getExamid() {
		return this.examid;
	}

	public void setExamid(Integer examid) {
		this.examid = examid;
	}

	@Column(name = "examname", nullable = false, length = 100)
	public String getExamname() {
		return this.examname;
	}

	public void setExamname(String examname) {
		this.examname = examname;
	}

	@Column(name = "examtypeid", nullable = false)
	public int getExamtypeid() {
		return this.examtypeid;
	}

	public void setExamtypeid(int examtypeid) {
		this.examtypeid = examtypeid;
	}

	@Column(name = "status")
	public Boolean getStatus() {
		return this.status;
	}

	public void setStatus(Boolean status) {
		this.status = status;
	}

}
