package com.leafsoft.persistance;
// Generated Dec 4, 2016 8:22:21 PM by Hibernate Tools 5.1.0.Alpha1

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * OrgDetails generated by hbm2java
 */
@Entity
@Table(name = "OrgDetails", catalog = "orgdb")
public class OrgDetails implements java.io.Serializable {

	private Integer orgid;
	private String orgname;
	private String address;
	private String state;
	private String city;
	private String zipcode;
	private String timetype;
	private String dateformat;
	private String currencycode;
	private long createdtime;
	private byte status;
	private String country;

	public OrgDetails() {
	}

	public OrgDetails(String orgname, long createdtime, byte status, String country) {
		this.orgname = orgname;
		this.createdtime = createdtime;
		this.status = status;
		this.country = country;
	}

	public OrgDetails(String orgname, String address, String state, String city, String zipcode, String timetype,
			String dateformat, String currencycode, long createdtime, byte status, String country) {
		this.orgname = orgname;
		this.address = address;
		this.state = state;
		this.city = city;
		this.zipcode = zipcode;
		this.timetype = timetype;
		this.dateformat = dateformat;
		this.currencycode = currencycode;
		this.createdtime = createdtime;
		this.status = status;
		this.country = country;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "orgid", unique = true, nullable = false)
	public Integer getOrgid() {
		return this.orgid;
	}

	public void setOrgid(Integer orgid) {
		this.orgid = orgid;
	}

	@Column(name = "orgname", nullable = false, length = 100)
	public String getOrgname() {
		return this.orgname;
	}

	public void setOrgname(String orgname) {
		this.orgname = orgname;
	}

	@Column(name = "address")
	public String getAddress() {
		return this.address;
	}

	public void setAddress(String address) {
		this.address = address;
	}

	@Column(name = "state", length = 75)
	public String getState() {
		return this.state;
	}

	public void setState(String state) {
		this.state = state;
	}

	@Column(name = "city", length = 75)
	public String getCity() {
		return this.city;
	}

	public void setCity(String city) {
		this.city = city;
	}

	@Column(name = "zipcode", length = 50)
	public String getZipcode() {
		return this.zipcode;
	}

	public void setZipcode(String zipcode) {
		this.zipcode = zipcode;
	}

	@Column(name = "timetype", length = 25)
	public String getTimetype() {
		return this.timetype;
	}

	public void setTimetype(String timetype) {
		this.timetype = timetype;
	}

	@Column(name = "dateformat", length = 25)
	public String getDateformat() {
		return this.dateformat;
	}

	public void setDateformat(String dateformat) {
		this.dateformat = dateformat;
	}

	@Column(name = "currencycode", length = 25)
	public String getCurrencycode() {
		return this.currencycode;
	}

	public void setCurrencycode(String currencycode) {
		this.currencycode = currencycode;
	}

	@Column(name = "createdtime", nullable = false)
	public long getCreatedtime() {
		return this.createdtime;
	}

	public void setCreatedtime(long createdtime) {
		this.createdtime = createdtime;
	}

	@Column(name = "status", nullable = false)
	public byte getStatus() {
		return this.status;
	}

	public void setStatus(byte status) {
		this.status = status;
	}

	@Column(name = "country", nullable = false, length = 100)
	public String getCountry() {
		return this.country;
	}

	public void setCountry(String country) {
		this.country = country;
	}

}
