package com.leafsoft.persistance;
// Generated Dec 4, 2016 8:22:21 PM by Hibernate Tools 5.1.0.Alpha1

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * OrgUsers generated by hbm2java
 */
@Entity
@Table(name = "OrgUsers", catalog = "orgdb")
public class OrgUsers implements java.io.Serializable {

	private Integer luid;
	private String username;
	private String email;
	private String password;
	private long createtime;
	private Integer defaultorgid;
	private int enabled;

	public OrgUsers() {
	}

	public OrgUsers(String username, long createtime, int enabled) {
		this.username = username;
		this.createtime = createtime;
		this.enabled = enabled;
	}

	public OrgUsers(String username, String email, String password, long createtime, Integer defaultorgid,
			int enabled) {
		this.username = username;
		this.email = email;
		this.password = password;
		this.createtime = createtime;
		this.defaultorgid = defaultorgid;
		this.enabled = enabled;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "luid", unique = true, nullable = false)
	public Integer getLuid() {
		return this.luid;
	}

	public void setLuid(Integer luid) {
		this.luid = luid;
	}

	@Column(name = "username", nullable = false, length = 100)
	public String getUsername() {
		return this.username;
	}

	public void setUsername(String username) {
		this.username = username;
	}

	@Column(name = "email", length = 50)
	public String getEmail() {
		return this.email;
	}

	public void setEmail(String email) {
		this.email = email;
	}

	@Column(name = "password", length = 100)
	public String getPassword() {
		return this.password;
	}

	public void setPassword(String password) {
		this.password = password;
	}

	@Column(name = "createtime", nullable = false)
	public long getCreatetime() {
		return this.createtime;
	}

	public void setCreatetime(long createtime) {
		this.createtime = createtime;
	}

	@Column(name = "defaultorgid")
	public Integer getDefaultorgid() {
		return this.defaultorgid;
	}

	public void setDefaultorgid(Integer defaultorgid) {
		this.defaultorgid = defaultorgid;
	}

	@Column(name = "enabled", nullable = false)
	public int getEnabled() {
		return this.enabled;
	}

	public void setEnabled(int enabled) {
		this.enabled = enabled;
	}

}
