package com.leafsoft.persistance;
// Generated Dec 4, 2016 8:22:21 PM by Hibernate Tools 5.1.0.Alpha1

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.UniqueConstraint;

/**
 * OrgUserRoles generated by hbm2java
 */
@Entity
@Table(name = "OrgUserRoles", catalog = "orgdb", uniqueConstraints = @UniqueConstraint(columnNames = { "rolename",
		"luid", "orgid" }) )
public class OrgUserRoles implements java.io.Serializable {

	private Integer userRoleId;
	private int orgid;
	private int luid;
	private String rolename;

	public OrgUserRoles() {
	}

	public OrgUserRoles(int orgid, int luid, String rolename) {
		this.orgid = orgid;
		this.luid = luid;
		this.rolename = rolename;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "user_role_id", unique = true, nullable = false)
	public Integer getUserRoleId() {
		return this.userRoleId;
	}

	public void setUserRoleId(Integer userRoleId) {
		this.userRoleId = userRoleId;
	}

	@Column(name = "orgid", nullable = false)
	public int getOrgid() {
		return this.orgid;
	}

	public void setOrgid(int orgid) {
		this.orgid = orgid;
	}

	@Column(name = "luid", nullable = false)
	public int getLuid() {
		return this.luid;
	}

	public void setLuid(int luid) {
		this.luid = luid;
	}

	@Column(name = "rolename", nullable = false, length = 100)
	public String getRolename() {
		return this.rolename;
	}

	public void setRolename(String rolename) {
		this.rolename = rolename;
	}

}
