package com.leafsoft.persistance;
// Generated Dec 4, 2016 10:43:15 PM by Hibernate Tools 3.6.0.Final

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * StaffSubjectCourseHistory generated by hbm2java
 */
@Entity
@Table(name = "StaffSubjectCourseHistory", catalog = "userdb")
public class StaffSubjectCourseHistory implements java.io.Serializable {

	private Integer staffsubjectcourseid;
	private int staffid;
	private int subjectid;
	private Date acadamicyear;
	private int courseid;

	public StaffSubjectCourseHistory() {
	}

	public StaffSubjectCourseHistory(int staffid, int subjectid, int courseid) {
		this.staffid = staffid;
		this.subjectid = subjectid;
		this.courseid = courseid;
	}

	public StaffSubjectCourseHistory(int staffid, int subjectid, Date acadamicyear, int courseid) {
		this.staffid = staffid;
		this.subjectid = subjectid;
		this.acadamicyear = acadamicyear;
		this.courseid = courseid;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "staffsubjectcourseid", unique = true, nullable = false)
	public Integer getStaffsubjectcourseid() {
		return this.staffsubjectcourseid;
	}

	public void setStaffsubjectcourseid(Integer staffsubjectcourseid) {
		this.staffsubjectcourseid = staffsubjectcourseid;
	}

	@Column(name = "staffid", nullable = false)
	public int getStaffid() {
		return this.staffid;
	}

	public void setStaffid(int staffid) {
		this.staffid = staffid;
	}

	@Column(name = "subjectid", nullable = false)
	public int getSubjectid() {
		return this.subjectid;
	}

	public void setSubjectid(int subjectid) {
		this.subjectid = subjectid;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "acadamicyear", length = 0)
	public Date getAcadamicyear() {
		return this.acadamicyear;
	}

	public void setAcadamicyear(Date acadamicyear) {
		this.acadamicyear = acadamicyear;
	}

	@Column(name = "courseid", nullable = false)
	public int getCourseid() {
		return this.courseid;
	}

	public void setCourseid(int courseid) {
		this.courseid = courseid;
	}

}
