package com.leafsoft.persistance;
// Generated Dec 4, 2016 10:43:15 PM by Hibernate Tools 3.6.0.Final

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * StaffQualification generated by hbm2java
 */
@Entity
@Table(name = "StaffQualification", catalog = "userdb")
public class StaffQualification implements java.io.Serializable {

	private Integer id;
	private Date qdate;
	private String institution;
	private String type;
	private double grade;
	private double percentage;
	private int staffid;

	public StaffQualification() {
	}

	public StaffQualification(Date qdate, double grade, double percentage, int staffid) {
		this.qdate = qdate;
		this.grade = grade;
		this.percentage = percentage;
		this.staffid = staffid;
	}

	public StaffQualification(Date qdate, String institution, String type, double grade, double percentage,
			int staffid) {
		this.qdate = qdate;
		this.institution = institution;
		this.type = type;
		this.grade = grade;
		this.percentage = percentage;
		this.staffid = staffid;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "id", unique = true, nullable = false)
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "qdate", nullable = false, length = 19)
	public Date getQdate() {
		return this.qdate;
	}

	public void setQdate(Date qdate) {
		this.qdate = qdate;
	}

	@Column(name = "institution")
	public String getInstitution() {
		return this.institution;
	}

	public void setInstitution(String institution) {
		this.institution = institution;
	}

	@Column(name = "type", length = 50)
	public String getType() {
		return this.type;
	}

	public void setType(String type) {
		this.type = type;
	}

	@Column(name = "grade", nullable = false, precision = 22, scale = 0)
	public double getGrade() {
		return this.grade;
	}

	public void setGrade(double grade) {
		this.grade = grade;
	}

	@Column(name = "percentage", nullable = false, precision = 22, scale = 0)
	public double getPercentage() {
		return this.percentage;
	}

	public void setPercentage(double percentage) {
		this.percentage = percentage;
	}

	@Column(name = "staffid", nullable = false)
	public int getStaffid() {
		return this.staffid;
	}

	public void setStaffid(int staffid) {
		this.staffid = staffid;
	}

}
