package com.leafsoft.persistance;
// Generated Dec 4, 2016 10:43:15 PM by Hibernate Tools 3.6.0.Final

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * StudentAcadamicHistory generated by hbm2java
 */
@Entity
@Table(name = "StudentAcadamicHistory", catalog = "userdb")
public class StudentAcadamicHistory implements java.io.Serializable {

	private Integer studenthistoryid;
	private byte historytype;
	private int examsubjectid;
	private int studentid;
	private int studentcoursehistoryid;
	private double mark;
	private double grade;

	public StudentAcadamicHistory() {
	}

	public StudentAcadamicHistory(byte historytype, int examsubjectid, int studentid, int studentcoursehistoryid,
			double mark, double grade) {
		this.historytype = historytype;
		this.examsubjectid = examsubjectid;
		this.studentid = studentid;
		this.studentcoursehistoryid = studentcoursehistoryid;
		this.mark = mark;
		this.grade = grade;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "studenthistoryid", unique = true, nullable = false)
	public Integer getStudenthistoryid() {
		return this.studenthistoryid;
	}

	public void setStudenthistoryid(Integer studenthistoryid) {
		this.studenthistoryid = studenthistoryid;
	}

	@Column(name = "historytype", nullable = false)
	public byte getHistorytype() {
		return this.historytype;
	}

	public void setHistorytype(byte historytype) {
		this.historytype = historytype;
	}

	@Column(name = "examsubjectid", nullable = false)
	public int getExamsubjectid() {
		return this.examsubjectid;
	}

	public void setExamsubjectid(int examsubjectid) {
		this.examsubjectid = examsubjectid;
	}

	@Column(name = "studentid", nullable = false)
	public int getStudentid() {
		return this.studentid;
	}

	public void setStudentid(int studentid) {
		this.studentid = studentid;
	}

	@Column(name = "studentcoursehistoryid", nullable = false)
	public int getStudentcoursehistoryid() {
		return this.studentcoursehistoryid;
	}

	public void setStudentcoursehistoryid(int studentcoursehistoryid) {
		this.studentcoursehistoryid = studentcoursehistoryid;
	}

	@Column(name = "mark", nullable = false, precision = 22, scale = 0)
	public double getMark() {
		return this.mark;
	}

	public void setMark(double mark) {
		this.mark = mark;
	}

	@Column(name = "grade", nullable = false, precision = 22, scale = 0)
	public double getGrade() {
		return this.grade;
	}

	public void setGrade(double grade) {
		this.grade = grade;
	}

}
