package com.leafsoft.persistance;
// Generated Dec 4, 2016 10:43:15 PM by Hibernate Tools 3.6.0.Final

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * StudentDetails generated by hbm2java
 */
@Entity
@Table(name = "StudentDetails", catalog = "userdb")
public class StudentDetails implements java.io.Serializable {

	private Integer studentid;
	private String studentname;
	private Date dob;
	private byte gender;
	private Boolean status;
	private long regdate;
	private int familyid;

	public StudentDetails() {
	}

	public StudentDetails(String studentname, byte gender, long regdate, int familyid) {
		this.studentname = studentname;
		this.gender = gender;
		this.regdate = regdate;
		this.familyid = familyid;
	}

	public StudentDetails(String studentname, Date dob, byte gender, Boolean status, long regdate, int familyid) {
		this.studentname = studentname;
		this.dob = dob;
		this.gender = gender;
		this.status = status;
		this.regdate = regdate;
		this.familyid = familyid;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "studentid", unique = true, nullable = false)
	public Integer getStudentid() {
		return this.studentid;
	}

	public void setStudentid(Integer studentid) {
		this.studentid = studentid;
	}

	@Column(name = "studentname", nullable = false, length = 100)
	public String getStudentname() {
		return this.studentname;
	}

	public void setStudentname(String studentname) {
		this.studentname = studentname;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "dob", length = 10)
	public Date getDob() {
		return this.dob;
	}

	public void setDob(Date dob) {
		this.dob = dob;
	}

	@Column(name = "gender", nullable = false)
	public byte getGender() {
		return this.gender;
	}

	public void setGender(byte gender) {
		this.gender = gender;
	}

	@Column(name = "status")
	public Boolean getStatus() {
		return this.status;
	}

	public void setStatus(Boolean status) {
		this.status = status;
	}

	@Column(name = "regdate", nullable = false)
	public long getRegdate() {
		return this.regdate;
	}

	public void setRegdate(long regdate) {
		this.regdate = regdate;
	}

	@Column(name = "familyid", nullable = false)
	public int getFamilyid() {
		return this.familyid;
	}

	public void setFamilyid(int familyid) {
		this.familyid = familyid;
	}

}
