package com.leafsoft.persistance;
// Generated Dec 4, 2016 10:43:15 PM by Hibernate Tools 3.6.0.Final

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * StudentCourseHistory generated by hbm2java
 */
@Entity
@Table(name = "StudentCourseHistory", catalog = "userdb")
public class StudentCourseHistory implements java.io.Serializable {

	private Integer studentcoursehistoryid;
	private int studentid;
	private int courseid;
	private Date acadamicyear;

	public StudentCourseHistory() {
	}

	public StudentCourseHistory(int studentid, int courseid) {
		this.studentid = studentid;
		this.courseid = courseid;
	}

	public StudentCourseHistory(int studentid, int courseid, Date acadamicyear) {
		this.studentid = studentid;
		this.courseid = courseid;
		this.acadamicyear = acadamicyear;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "studentcoursehistoryid", unique = true, nullable = false)
	public Integer getStudentcoursehistoryid() {
		return this.studentcoursehistoryid;
	}

	public void setStudentcoursehistoryid(Integer studentcoursehistoryid) {
		this.studentcoursehistoryid = studentcoursehistoryid;
	}

	@Column(name = "studentid", nullable = false)
	public int getStudentid() {
		return this.studentid;
	}

	public void setStudentid(int studentid) {
		this.studentid = studentid;
	}

	@Column(name = "courseid", nullable = false)
	public int getCourseid() {
		return this.courseid;
	}

	public void setCourseid(int courseid) {
		this.courseid = courseid;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "acadamicyear", length = 0)
	public Date getAcadamicyear() {
		return this.acadamicyear;
	}

	public void setAcadamicyear(Date acadamicyear) {
		this.acadamicyear = acadamicyear;
	}

}
