package com.leafsoft.persistance;
// Generated Dec 4, 2016 10:43:15 PM by Hibernate Tools 3.6.0.Final

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * Subjects generated by hbm2java
 */
@Entity
@Table(name = "Subjects", catalog = "userdb")
public class Subjects implements java.io.Serializable {

	private Integer subjectid;
	private String subjectname;
	private byte subjecttype;
	private Boolean status;

	public Subjects() {
	}

	public Subjects(String subjectname, byte subjecttype) {
		this.subjectname = subjectname;
		this.subjecttype = subjecttype;
	}

	public Subjects(String subjectname, byte subjecttype, Boolean status) {
		this.subjectname = subjectname;
		this.subjecttype = subjecttype;
		this.status = status;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "subjectid", unique = true, nullable = false)
	public Integer getSubjectid() {
		return this.subjectid;
	}

	public void setSubjectid(Integer subjectid) {
		this.subjectid = subjectid;
	}

	@Column(name = "subjectname", nullable = false, length = 100)
	public String getSubjectname() {
		return this.subjectname;
	}

	public void setSubjectname(String subjectname) {
		this.subjectname = subjectname;
	}

	@Column(name = "subjecttype", nullable = false)
	public byte getSubjecttype() {
		return this.subjecttype;
	}

	public void setSubjecttype(byte subjecttype) {
		this.subjecttype = subjecttype;
	}

	@Column(name = "status")
	public Boolean getStatus() {
		return this.status;
	}

	public void setStatus(Boolean status) {
		this.status = status;
	}

}
